#!/bin/bash
cat /etc/passwd
total 36
drwxr-xr-x 2 root root 179 Mar 13 16:29 .
drwxr-xr-x 6 root root 121 Mar 13 15:48 ..
-rwxr--r-- 1 root root  32 Mar 13 15:56 0-hello_world
-rwxr--r-- 1 root root  27 Mar 13 16:18 1-confused_smiley
-rw-r--r-- 1 root root  28 Mar 13 16:20 2-hellofile
-rw-r--r-- 1 root root  39 Mar 13 16:21 3-twofiles
-rw-r--r-- 1 root root  29 Mar 13 16:24 4-lastlines
-rw-r--r-- 1 root root  30 Mar 13 16:25 5-firstlines
-rw-r--r-- 1 root root  36 Mar 13 16:27 6-third_line
-rw-r--r-- 1 root root  75 Mar 13 16:29 7-file
-rwxr--r-- 1 root root  10 Mar 13 15:49 README.md
